# Generated by Django 4.1 on 2023-01-12 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteBin',
            fields=[
                ('bin_ID', models.AutoField(primary_key=True, serialize=False)),
                ('identity', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=250)),
                ('landmark', models.CharField(max_length=200)),
                ('municipality', models.CharField(max_length=30)),
            ],
        ),
    ]
