# Generated by Django 4.1 on 2023-01-12 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0002_wastebin'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastebin',
            name='photo',
            field=models.ImageField(default='sdsd', upload_to='wastebin'),
            preserve_default=False,
        ),
    ]
