# Generated by Django 4.1 on 2023-01-12 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0003_wastebin_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection_Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.BigIntegerField()),
                ('address', models.TextField()),
                ('photo', models.ImageField(upload_to='collection_agent')),
                ('vehicle_number', models.CharField(max_length=100)),
                ('vehicle_image', models.ImageField(upload_to='collection_vehicle')),
                ('username', models.CharField(max_length=100)),
                ('user_status', models.CharField(default='active', max_length=100)),
                ('municipality', models.CharField(max_length=100)),
            ],
        ),
    ]
