# Generated by Django 4.1 on 2023-01-12 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0004_collection_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastebin',
            name='agent',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
