# Generated by Django 4.1 on 2023-01-12 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0005_wastebin_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastebin',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
